"""add is_private to Photo

Revision ID: 427a297ecb76
Revises: bb36537b7f6b
Create Date: 2025-09-07 14:55:55.206771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427a297ecb76'
down_revision = 'bb36537b7f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_cover')
    op.drop_table('photo')
    op.drop_table('story_image')
    op.drop_table('album_covers')
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    op.create_table('album_covers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=False),
    sa.Column('cover_public_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id')
    )
    op.create_table('story_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_cover',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('album_id', sa.INTEGER(), nullable=True),
    sa.Column('cover_public_id', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
